name: arc_test Workflow

permissions:
  contents: read

on:
  workflow_dispatch: 
    inputs:
      custom_input:
        description: 'Input passed from Power Automate workflow'
        required: true

# on: [workflow_dispatch]

jobs:
  arc_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r arc/requirements.txt
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/arc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run arc_test
        env:
            AGO_USERNAME: ${{ secrets.AGO_USERNAME }}
            AGO_PASSWORD: ${{ secrets.AGO_PASSWORD }}
            AGO_PORTAL: ${{ secrets.AGO_PORTAL }}
            OID_POWER_AUTOMATE: ${{ inputs.custom_input}}

        run: python arc/arc_test.py